# Site Settings
title:               Keira's Blog
tagline:             a way to  records the learning 
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://danyanq.github.io/personalblog/"
author:
  name:              "Keira Qiu"
  email:             "qiudanyan86@163.com"
  twitter:           "qiudanyan"
  instagram:         "qiudanyan"
  github:            "danyanq"
  facebook:          "danyanq"
  linkedin:          "danyanq"
navigation:
- title: About me 
  url: /about me 
- title: Learning english
  url: /learning english
- title: learning front-end
  url: /learning front-end

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
